version: "3"
services: 
  postgres:
    image: postgres
    volumes:
      - "postgresql-volume:/var/lib/postgresql/data"
    # tmpfs:
      # - /var/lib/postgresql/data
    # network_mode: "host"
  redis:
    image: redis
    # network_mode: "host"


volumes:
  postgresql-volume:
