version: "3"
services:
  apache:
    image: francois/apache-hostname 
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "18081:80"
    networks:
      - demo-network
  visualiser:
    image: dockersamples/visualizer
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "18080:8080"
    networks:
      - demo-network

networks:
  demo-network:
    driver: overlay


# docker run -it --rm -t devth/alpine-bench -n3 http://google.com/